### ISSUE TITLE
cannot build (ApplicationInsights.config not found)

### ISSUE THREAD

**Issue by Trolldemorted** [PieEatingNinjas/PivotWithoutSwipe#1]
i cloned this project, opened up the .sln with VS 2015, pressed F5 and it does not build:

```
1>------ Erstellen gestartet: Projekt: PieEatingNinjas.PivotWithoutSwipe, Konfiguration: Debug x86 ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(4106,5): error MSB3030: Datei "C:\Users\XXXXX\repositories\PivotWithoutSwipe\PieEatingNinjas.PivotWithoutSwipe\PieEatingNinjas.PivotWithoutSwipe\ApplicationInsights.config" konnte nicht kopiert werden, da die Datei nicht gefunden wurde.
========== Erstellen: 0 erfolgreich, 1 fehlerhaft, 0 aktuell, 0 übersprungen ==========
```

The error message says "[] could not be copied, because the file was not found".
Am i doing something wrong?

**Comment by PieEatingNinjas** [comment]
I'll take a look at it asap.
But I think that you could remove everything from ApplicationInsights from the code and references as it not needed.

**Comment by Trolldemorted** [comment]
yeah that did the trick!

should only the swipe-with-finger-behaviour be disabled? when i click the header, it still plays a slide-in animation.

**Comment by PieEatingNinjas** [comment]
Indeed. This code is about disabling the swipe gesture itself. All the other behavior of the Pivot control remains. So when clicking or tapping a header in the Pivot, the selected PivotItem will 'swipe' into place.

**Comment by Trolldemorted** [comment]
Any ideas on how to disable the animation? i asked on the [microsoft forums](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/0f7226ce-62cd-47a8-aa70-540767be07cd/disablechange-pivot-sliding-animation?forum=wpdevelop#0f7226ce-62cd-47a8-aa70-540767be07cd), and was directed here.

The animation might look good when you actually swipe, but on a desktop it is loony.

**Comment by PieEatingNinjas** [comment]
Good question. I'll try to see tomorrow how we could achieve this.

**Comment by Trolldemorted** [comment]
oh and vs2015 is compaining about MainPage.xaml (line 24ff):

`Cannot add instance of type 'Windows.UI.Xaml.Setter' to a collection of type 'Windows.UI.Xaml.SetterBaseCollection'`

**Comment by PieEatingNinjas** [comment]
Strange as I don't see this message and this is just the standard style that I only modified a bit.

**Comment by Trolldemorted** [comment]
that is odd...

which version of vs are you using? did you try cloning the repo again for a clean environment?

**Comment by PieEatingNinjas** [comment]
I use VS2015 Enterprise Update 3 and it is indeed a new clone of the repo.

**Comment by Trolldemorted** [comment]
I am running VS2015 Enterprise 2015, 14.0.25425.01 Update 3, and have also cloned the repo again.

Could it be user-settings-related? Or is my vs-installation missing some packages?

**Comment by Trolldemorted** [comment]
Looks like i am affected by [this bug](https://connect.microsoft.com/VisualStudio/feedback/details/3045072/xaml-template-copying-errors-across-vs-and-blend), sorry for bothering you - upgrading to vs2017 solved it, as the issuer stated.

nevertheless, any ideas for disabling the sliding animation would be great! I have also asked on [so](http://stackoverflow.com/questions/41371333/disable-change-pivot-animations-on-uwp) for help, btw.

**Comment by PieEatingNinjas** [comment]
No problem!
If I have some time today, I'll take a look on how to disable the sliding animation. Just to make sure we are on the same level here: you just want the content of the pivot to appear, omitting any animation when selecting an other pivot item?

**Comment by Trolldemorted** [comment]
exactly!

the animation should be suppressed (or i'd like to implement my own, e.g. a fade-in instead of a slide-in), and the header should appear selected immediately (and not after the animation finishes).

**Comment by Trolldemorted** [comment]
Did you have any luck? Neither stackoverflow nor microsoft's uwp forum could recommend a solution :|
